# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=30)),
                ('coin_price_bithumb', models.FloatField()),
                ('coin_price_poloniex', models.FloatField()),
                ('coin_pirce_kimchi', models.FloatField()),
                ('check_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
