# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_exchangerate_hanrivertemperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coindb',
            name='coin_pirce_kimchi',
        ),
    ]
