# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_auto_20171223_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poloniex',
            new_name='PoloniexDB',
        ),
    ]
