# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0007_auto_20171223_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitfinexDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=30)),
                ('coin_price', models.FloatField()),
                ('check_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CoinDB',
        ),
    ]
