# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0009_upbitdb_userdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='coin_count',
            field=models.FloatField(null=True),
        ),
    ]
